34 add event page
swciitg/icragee_mobile pull request #39
Opened 2024-09-02 05:39 UTC by Amore174

Implemented the UI, Navigation, and backend of the add event page.

2024-09-05 18:48 UTC, hardikroongta8 commented on lib/services/firestore_service.dart
There's already a class called DataService
put these functions in that class

2024-09-05 18:51 UTC, hardikroongta8 requested changes
There's already a class named DataService
Put the functions of FirestoreService in DataService class nd make them static

2024-09-07 05:30 UTC, Amore174 commented
merged firestore class in data service class

2024-09-07 05:52 UTC, hardikroongta8 approved these changes

2024-09-07 05:56 UTC, merged